// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Representation of a Constraint.
public struct Constraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var implementation: OneOf_Implementation? = nil

  /// Initialize a new instance of `Constraint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Constraint().with { $0.securityHealthAnalyticsModule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case securityHealthAnalyticsModule = "securityHealthAnalyticsModule"
    case securityHealthAnalyticsCustomModule = "securityHealthAnalyticsCustomModule"
    case orgPolicyConstraint = "orgPolicyConstraint"
    case orgPolicyConstraintCustom = "orgPolicyConstraintCustom"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var implementation: OneOf_Implementation? = nil
    let implementationCheckAndSet = {
      if implementation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'implementation'"))
      }
      implementation = $0
    }
    if let securityHealthAnalyticsModule = try container.decodeIfPresent(
      SecurityHealthAnalyticsModule?.self, forKey: .securityHealthAnalyticsModule)
    {
      try implementationCheckAndSet(.securityHealthAnalyticsModule(securityHealthAnalyticsModule))
    }
    if let securityHealthAnalyticsCustomModule = try container.decodeIfPresent(
      SecurityHealthAnalyticsCustomModule?.self, forKey: .securityHealthAnalyticsCustomModule)
    {
      try implementationCheckAndSet(
        .securityHealthAnalyticsCustomModule(securityHealthAnalyticsCustomModule))
    }
    if let orgPolicyConstraint = try container.decodeIfPresent(
      OrgPolicyConstraint?.self, forKey: .orgPolicyConstraint)
    {
      try implementationCheckAndSet(.orgPolicyConstraint(orgPolicyConstraint))
    }
    if let orgPolicyConstraintCustom = try container.decodeIfPresent(
      OrgPolicyConstraintCustom?.self, forKey: .orgPolicyConstraintCustom)
    {
      try implementationCheckAndSet(.orgPolicyConstraintCustom(orgPolicyConstraintCustom))
    }
    self.implementation = implementation
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.implementation {
      switch choice {
      case .securityHealthAnalyticsModule(let value):
        try container.encode(value, forKey: .securityHealthAnalyticsModule)
      case .securityHealthAnalyticsCustomModule(let value):
        try container.encode(value, forKey: .securityHealthAnalyticsCustomModule)
      case .orgPolicyConstraint(let value):
        try container.encode(value, forKey: .orgPolicyConstraint)
      case .orgPolicyConstraintCustom(let value):
        try container.encode(value, forKey: .orgPolicyConstraintCustom)
      }
    }
  }

  public enum OneOf_Implementation: Codable, Equatable, Sendable {
    /// Optional. SHA built-in detector.
    indirect case securityHealthAnalyticsModule(SecurityHealthAnalyticsModule?)
    /// Optional. SHA custom detector.
    indirect case securityHealthAnalyticsCustomModule(SecurityHealthAnalyticsCustomModule?)
    /// Optional. Org Policy builtin constraint.
    indirect case orgPolicyConstraint(OrgPolicyConstraint?)
    /// Optional. Org Policy custom constraint.
    indirect case orgPolicyConstraintCustom(OrgPolicyConstraintCustom?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securityposture.v1.Constraint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
