// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A custom constraint defined by customers which can *only* be applied to the
/// given resource types and organization.
///
/// By creating a custom constraint, customers can apply policies of this
/// custom constraint. *Creating a custom constraint itself does NOT apply any
/// policy enforcement*.
public struct CustomConstraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. Name of the constraint. This is unique within the organization.
  /// Format of the name should be
  ///
  /// -
  /// `organizations/{organization_id}/customConstraints/{custom_constraint_id}`
  ///
  /// Example: `organizations/123/customConstraints/custom.createOnlyE2TypeVms`
  ///
  /// The max length is 70 characters and the minimum length is 1. Note that the
  /// prefix `organizations/{organization_id}/customConstraints/` is not counted.
  public var name: Swift.String = Swift.String()

  /// Immutable. The resource instance type on which this policy applies. Format
  /// will be of the form : `<canonical service name>/<type>` Example:
  ///
  ///  - `compute.googleapis.com/Instance`.
  public var resourceTypes: [Swift.String] = []

  /// All the operations being applied for this constraint.
  public var methodTypes: [CustomConstraint.MethodType] = []

  /// Org policy condition/expression. For example:
  /// `resource.instanceName.matches("[production|test]_.*_(\d)+")` or,
  /// `resource.management.auto_upgrade == true`
  ///
  /// The max length of the condition is 1000 characters.
  public var condition: Swift.String = Swift.String()

  /// Allow or deny type.
  public var actionType: CustomConstraint.ActionType = CustomConstraint.ActionType()

  /// One line display name for the UI.
  /// The max length of the display_name is 200 characters.
  public var displayName: Swift.String = Swift.String()

  /// Detailed information about this custom policy constraint.
  /// The max length of the description is 2000 characters.
  public var description: Swift.String = Swift.String()

  /// Output only. The last time this custom constraint was updated. This
  /// represents the last time that the `CreateCustomConstraint` or
  /// `UpdateCustomConstraint` RPC was called
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `CustomConstraint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomConstraint().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The operation for which this constraint will be applied. To apply this
  /// constraint only when creating new VMs, the `method_types` should be
  /// `CREATE` only. To apply this constraint when creating or deleting
  /// VMs, the `method_types` should be `CREATE` and `DELETE`.
  ///
  /// `UPDATE` only custom constraints are not supported. Use `CREATE` or
  /// `CREATE, UPDATE`.
  public enum MethodType: Codable, Equatable, Sendable {
    /// Unspecified. Results in an error.
    case unspecified
    /// Constraint applied when creating the resource.
    case create
    /// Constraint applied when updating the resource.
    case update
    /// Constraint applied when deleting the resource.
    /// Not supported yet.
    case delete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .create: return 1
      case .update: return 2
      case .delete: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "METHOD_TYPE_UNSPECIFIED"
      case .create: return "CREATE"
      case .update: return "UPDATE"
      case .delete: return "DELETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MethodType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "METHOD_TYPE_UNSPECIFIED": self = .unspecified
      case "CREATE": self = .create
      case "UPDATE": self = .update
      case "DELETE": self = .delete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MethodType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .create
      case 2: self = .update
      case 3: self = .delete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .create: return try container.encode(1)
      case .update: return try container.encode(2)
      case .delete: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Allow or deny type.
  public enum ActionType: Codable, Equatable, Sendable {
    /// Unspecified. Results in an error.
    case unspecified
    /// Allowed action type.
    case allow
    /// Deny action type.
    case deny
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .allow: return 1
      case .deny: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACTION_TYPE_UNSPECIFIED"
      case .allow: return "ALLOW"
      case .deny: return "DENY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ActionType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACTION_TYPE_UNSPECIFIED": self = .unspecified
      case "ALLOW": self = .allow
      case "DENY": self = .deny
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ActionType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .allow
      case 2: self = .deny
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .allow: return try container.encode(1)
      case .deny: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securityposture.v1.CustomConstraint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
