// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// Defines the properties in a custom module configuration for Security
/// Health Analytics. Use the custom module configuration to create custom
/// detectors that generate custom findings for resources that you specify.
public struct CustomConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The CEL expression to evaluate to produce findings. When the
  /// expression evaluates to true against a resource, a finding is generated.
  public var predicate: GoogleType.Expr? = nil

  /// Optional. Custom output properties.
  public var customOutput: CustomConfig.CustomOutputSpec? = nil

  /// Required. The resource types that the custom module operates on. Each
  /// custom module can specify up to 5 resource types.
  public var resourceSelector: CustomConfig.ResourceSelector? = nil

  /// Required. The severity to assign to findings generated by the module.
  public var severity: CustomConfig.Severity = CustomConfig.Severity()

  /// Optional. Text that describes the vulnerability or misconfiguration that
  /// the custom module detects. This explanation is returned with each finding
  /// instance to help investigators understand the detected issue. The text must
  /// be enclosed in quotation marks.
  public var description: Swift.String = Swift.String()

  /// Optional. An explanation of the recommended steps that security teams can
  /// take to resolve the detected issue. This explanation is returned with each
  /// finding generated by this module in the `nextSteps` property of the finding
  /// JSON.
  public var recommendation: Swift.String = Swift.String()

  /// Initialize a new instance of `CustomConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomConfig().with { $0.predicate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A set of optional name-value pairs that define custom source properties to
  /// return with each finding that is generated by the custom module. The custom
  /// source properties that are defined here are included in the finding JSON
  /// under `sourceProperties`.
  public struct CustomOutputSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. A list of custom output properties to add to the finding.
    public var properties: [CustomConfig.CustomOutputSpec.Property] = []

    /// Initialize a new instance of `CustomOutputSpec`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomOutputSpec().with { $0.properties = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// An individual name-value pair that defines a custom source property.
    public struct Property: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. Name of the property for the custom output.
      public var name: Swift.String = Swift.String()

      /// Optional. The CEL expression for the custom output. A resource property
      /// can be specified to return the value of the property or a text string
      /// enclosed in quotation marks.
      public var valueExpression: GoogleType.Expr? = nil

      /// Initialize a new instance of `Property`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Property().with { $0.name = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.securityposture.v1.CustomConfig.CustomOutputSpec.Property"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securityposture.v1.CustomConfig.CustomOutputSpec"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Resource for selecting resource type.
  public struct ResourceSelector: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The resource types to run the detector on.
    public var resourceTypes: [Swift.String] = []

    /// Initialize a new instance of `ResourceSelector`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceSelector().with { $0.resourceTypes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securityposture.v1.CustomConfig.ResourceSelector"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines the valid value options for the severity of a finding.
  public enum Severity: Codable, Equatable, Sendable {
    /// Unspecified severity.
    case unspecified
    /// Critical severity.
    case critical
    /// High severity.
    case high
    /// Medium severity.
    case medium
    /// Low severity.
    case low
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .critical: return 1
      case .high: return 2
      case .medium: return 3
      case .low: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SEVERITY_UNSPECIFIED"
      case .critical: return "CRITICAL"
      case .high: return "HIGH"
      case .medium: return "MEDIUM"
      case .low: return "LOW"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Severity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SEVERITY_UNSPECIFIED": self = .unspecified
      case "CRITICAL": self = .critical
      case "HIGH": self = .high
      case "MEDIUM": self = .medium
      case "LOW": self = .low
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Severity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .critical
      case 2: self = .high
      case 3: self = .medium
      case 4: self = .low
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .critical: return try container.encode(1)
      case .high: return try container.encode(2)
      case .medium: return try container.encode(3)
      case .low: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securityposture.v1.CustomConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
