// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message for extracting existing policies on a workload as a Posture.
public struct ExtractPostureRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent resource name. The format of this value is as follows:
  /// `organizations/{organization}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. User provided identifier. It should be unique in scope of an
  /// Organization and location.
  public var postureId: Swift.String = Swift.String()

  /// Required. Workload from which the policies are to be extracted, it should
  /// belong to the same organization defined in parent. The format of this value
  /// varies depending on the scope of the request:
  /// - `folder/folderNumber`
  /// - `project/projectNumber`
  /// - `organization/organizationNumber`
  public var workload: Swift.String = Swift.String()

  /// Initialize a new instance of `ExtractPostureRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExtractPostureRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securityposture.v1.ExtractPostureRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
