// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Policy representation.
public struct Policy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. ID of the Policy that is user generated, immutable and unique
  /// within the scope of a policy set.
  public var policyId: Swift.String = Swift.String()

  /// Optional. Contains list of mapping for a Policy to a standard and control.
  public var complianceStandards: [Policy.ComplianceStandard] = []

  /// Required. Constraint details.
  public var constraint: Constraint? = nil

  /// Optional. Description of the Policy.
  public var description: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Policy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Policy().with { $0.policyId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let policyId = CodingKeys(stringValue: "policyId")
    static let complianceStandards = CodingKeys(stringValue: "complianceStandards")
    static let constraint = CodingKeys(stringValue: "constraint")
    static let description = CodingKeys(stringValue: "description")

    static let _knownKeys: Set<Swift.String> = [
      "policyId",
      "complianceStandards",
      "constraint",
      "description",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .policyId) {
      self.policyId = value
    }
    if let value = try container.decodeIfPresent(
      [Policy.ComplianceStandard].self, forKey: .complianceStandards)
    {
      self.complianceStandards = value
    }
    self.constraint = try container.decodeIfPresent(Constraint.self, forKey: .constraint)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.policyId, forKey: .policyId)
    try container.encode(self.complianceStandards, forKey: .complianceStandards)
    try container.encodeIfPresent(self.constraint, forKey: .constraint)
    try container.encode(self.description, forKey: .description)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Mapping for a Policy to standard and control.
  public struct ComplianceStandard: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The compliance standard that the Policy maps to, e.g.: CIS-2.0.
    public var standard: Swift.String = Swift.String()

    /// Optional. Control mapping provided by user for this Policy. e.g.: 1.5.
    public var control: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `ComplianceStandard`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ComplianceStandard().with { $0.standard = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let standard = CodingKeys(stringValue: "standard")
      static let control = CodingKeys(stringValue: "control")

      static let _knownKeys: Set<Swift.String> = [
        "standard",
        "control",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .standard) {
        self.standard = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .control) {
        self.control = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.standard, forKey: .standard)
      try container.encode(self.control, forKey: .control)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securityposture.v1.Policy.ComplianceStandard"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securityposture.v1.Policy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
