// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Policy representation.
public struct Policy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. ID of the Policy that is user generated, immutable and unique
  /// within the scope of a policy set.
  public var policyId: Swift.String = Swift.String()

  /// Optional. Contains list of mapping for a Policy to a standard and control.
  public var complianceStandards: [Policy.ComplianceStandard] = []

  /// Required. Constraint details.
  public var constraint: Constraint? = nil

  /// Optional. Description of the Policy.
  public var description: Swift.String = Swift.String()

  /// Initialize a new instance of `Policy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Policy().with { $0.policyId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Mapping for a Policy to standard and control.
  public struct ComplianceStandard: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The compliance standard that the Policy maps to, e.g.: CIS-2.0.
    public var standard: Swift.String = Swift.String()

    /// Optional. Control mapping provided by user for this Policy. e.g.: 1.5.
    public var control: Swift.String = Swift.String()

    /// Initialize a new instance of `ComplianceStandard`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ComplianceStandard().with { $0.standard = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.securityposture.v1.Policy.ComplianceStandard"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securityposture.v1.Policy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
