// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Postures
/// Definition of a Posture.
public struct Posture: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Identifier. The name of this Posture resource, in the format of
  /// organizations/{org_id}/locations/{location_id}/postures/{posture}.
  public var name: Swift.String = Swift.String()

  /// Required. State of Posture resource.
  public var state: Posture.State = Posture.State()

  /// Output only. Immutable. The revision ID of the posture.
  /// The format is an 8-character hexadecimal string.
  /// https://google.aip.dev/162
  public var revisionId: Swift.String = Swift.String()

  /// Output only. The timestamp that the posture was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp that the posture was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. User provided description of the posture.
  public var description: Swift.String = Swift.String()

  /// Required. List of Policy sets.
  public var policySets: [PolicySet] = []

  /// Optional. An opaque tag indicating the current version of the Posture, used
  /// for concurrency control. When the `Posture` is returned from either a
  /// `GetPosture` or a `ListPostures` request, this `etag` indicates the version
  /// of the current `Posture` to use when executing a read-modify-write loop.
  ///
  /// When the `Posture` is used in a `UpdatePosture` method, use the `etag`
  /// value that was returned from a `GetPosture` request as part of a
  /// read-modify-write loop for concurrency control. Not setting the `etag` in a
  /// `UpdatePosture` request will result in an unconditional write of the
  /// `Posture`.
  public var etag: Swift.String = Swift.String()

  /// Optional. User annotations. These attributes can only be set and used by
  /// the user, and not by Google Security Postures.
  /// .
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. Whether or not this Posture is in the process of being
  /// updated.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Posture`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Posture().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State of a Posture.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified operation state.
    case unspecified
    /// The Posture is marked deprecated when it is not in use by the user.
    case deprecated
    /// The Posture is created successfully but is not yet ready for usage.
    case draft
    /// The Posture state is active. Ready for use/deployments.
    case active
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .deprecated: return 1
      case .draft: return 2
      case .active: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .deprecated: return "DEPRECATED"
      case .draft: return "DRAFT"
      case .active: return "ACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "DEPRECATED": self = .deprecated
      case "DRAFT": self = .draft
      case "ACTIVE": self = .active
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .deprecated
      case 2: self = .draft
      case 3: self = .active
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .deprecated: return try container.encode(1)
      case .draft: return try container.encode(2)
      case .active: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securityposture.v1.Posture"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
