// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ========================== PostureDeployments ==========================
/// Message describing PostureDeployment resource.
public struct PostureDeployment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of this PostureDeployment resource, in the format of
  /// organizations/{organization}/locations/{location_id}/postureDeployments/{postureDeployment}.
  public var name: Swift.String = Swift.String()

  /// Required. Target resource where the Posture will be deployed. Currently
  /// supported resources are of types: projects/projectNumber,
  /// folders/folderNumber, organizations/organizationNumber.
  public var targetResource: Swift.String = Swift.String()

  /// Output only. State of PostureDeployment resource.
  public var state: PostureDeployment.State = PostureDeployment.State()

  /// Required. Posture that needs to be deployed.
  /// Format:
  /// organizations/{org_id}/locations/{location_id}/postures/<posture>
  /// Example:
  /// organizations/99/locations/global/postures/les-miserables.
  public var postureId: Swift.String = Swift.String()

  /// Required. Revision_id of the Posture that is to be deployed.
  public var postureRevisionId: Swift.String = Swift.String()

  /// Output only. The timestamp that the PostureDeployment was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The timestamp that the PostureDeployment was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. User provided description of the PostureDeployment.
  public var description: Swift.String = Swift.String()

  /// Optional. An opaque tag indicating the current version of the
  /// PostureDeployment, used for concurrency control. When the
  /// `PostureDeployment` is returned from either a `GetPostureDeployment` or a
  /// `ListPostureDeployments` request, this `etag` indicates the version of the
  /// current `PostureDeployment` to use when executing a read-modify-write loop.
  ///
  /// When the `PostureDeployment` is used in a `UpdatePostureDeployment` method,
  /// use the `etag` value that was returned from a `GetPostureDeployment`
  /// request as part of a read-modify-write loop for concurrency control. Not
  /// setting the `etag` in a `UpdatePostureDeployment` request will result in an
  /// unconditional write of the `PostureDeployment`.
  public var etag: Swift.String = Swift.String()

  /// Optional. User annotations. These attributes can only be set and used by
  /// the user, and not by Google Security Postures.
  /// .
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. Whether or not this Posture is in the process of being
  /// updated.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Output only. This is a output only optional field which will be filled in
  /// case where PostureDeployment state is UPDATE_FAILED or CREATE_FAILED or
  /// DELETE_FAILED. It denotes the desired Posture.
  public var desiredPostureId: Swift.String = Swift.String()

  /// Output only. Output only optional field which provides revision_id of the
  /// desired_posture_id.
  public var desiredPostureRevisionId: Swift.String = Swift.String()

  /// Output only. This is a output only optional field which will be filled in
  /// case where PostureDeployment enters a failure state like UPDATE_FAILED or
  /// CREATE_FAILED or DELETE_FAILED.
  public var failureMessage: Swift.String = Swift.String()

  /// Initialize a new instance of `PostureDeployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PostureDeployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State of a PostureDeployment.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified operation state.
    case unspecified
    /// The PostureDeployment is being created.
    case creating
    /// The PostureDeployment is being deleted.
    case deleting
    /// The PostureDeployment state is being updated.
    case updating
    /// The PostureDeployment state is active and in use.
    case active
    /// The PostureDeployment creation failed.
    case createFailed
    /// The PostureDeployment update failed.
    case updateFailed
    /// The PostureDeployment deletion failed.
    case deleteFailed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .deleting: return 2
      case .updating: return 3
      case .active: return 4
      case .createFailed: return 5
      case .updateFailed: return 6
      case .deleteFailed: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .updating: return "UPDATING"
      case .active: return "ACTIVE"
      case .createFailed: return "CREATE_FAILED"
      case .updateFailed: return "UPDATE_FAILED"
      case .deleteFailed: return "DELETE_FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "UPDATING": self = .updating
      case "ACTIVE": self = .active
      case "CREATE_FAILED": self = .createFailed
      case "UPDATE_FAILED": self = .updateFailed
      case "DELETE_FAILED": self = .deleteFailed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .deleting
      case 3: self = .updating
      case 4: self = .active
      case 5: self = .createFailed
      case 6: self = .updateFailed
      case 7: self = .deleteFailed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .deleting: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .active: return try container.encode(4)
      case .createFailed: return try container.encode(5)
      case .updateFailed: return try container.encode(6)
      case .deleteFailed: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securityposture.v1.PostureDeployment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
