// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class SecurityPostureLogging: SecurityPostureStub {
    let inner: any SecurityPostureStub
    let logger: Logger

    public init(_ inner: any SecurityPostureStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-securityposture-v1"
      logger[metadataKey: "gcp.client.service"] = "securityposture"
      logger[metadataKey: "gcp.experimental.swift.client"] = "SecurityPosture"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listPostures(
      request: ListPosturesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.ListPosturesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPostures",
        action: {
          (r: ListPosturesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecuritypostureV1.ListPosturesResponse
          in
          return try await self.inner.listPostures(request: r, options: o)
        })
    }

    public func listPostureRevisions(
      request: ListPostureRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.ListPostureRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPostureRevisions",
        action: {
          (r: ListPostureRevisionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecuritypostureV1.ListPostureRevisionsResponse
          in
          return try await self.inner.listPostureRevisions(request: r, options: o)
        })
    }

    public func getPosture(
      request: GetPostureRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.Posture {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPosture",
        action: {
          (r: GetPostureRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecuritypostureV1.Posture
          in
          return try await self.inner.getPosture(request: r, options: o)
        })
    }

    public func createPosture(
      request: CreatePostureRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPosture",
        action: {
          (r: CreatePostureRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPosture(request: r, options: o)
        })
    }

    public func updatePosture(
      request: UpdatePostureRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePosture",
        action: {
          (r: UpdatePostureRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePosture(request: r, options: o)
        })
    }

    public func deletePosture(
      request: DeletePostureRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePosture",
        action: {
          (r: DeletePostureRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePosture(request: r, options: o)
        })
    }

    public func extractPosture(
      request: ExtractPostureRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "extractPosture",
        action: {
          (r: ExtractPostureRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.extractPosture(request: r, options: o)
        })
    }

    public func listPostureDeployments(
      request: ListPostureDeploymentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.ListPostureDeploymentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPostureDeployments",
        action: {
          (r: ListPostureDeploymentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecuritypostureV1.ListPostureDeploymentsResponse
          in
          return try await self.inner.listPostureDeployments(request: r, options: o)
        })
    }

    public func getPostureDeployment(
      request: GetPostureDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.PostureDeployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPostureDeployment",
        action: {
          (r: GetPostureDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecuritypostureV1.PostureDeployment
          in
          return try await self.inner.getPostureDeployment(request: r, options: o)
        })
    }

    public func createPostureDeployment(
      request: CreatePostureDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPostureDeployment",
        action: {
          (r: CreatePostureDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPostureDeployment(request: r, options: o)
        })
    }

    public func updatePostureDeployment(
      request: UpdatePostureDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePostureDeployment",
        action: {
          (r: UpdatePostureDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePostureDeployment(request: r, options: o)
        })
    }

    public func deletePostureDeployment(
      request: DeletePostureDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePostureDeployment",
        action: {
          (r: DeletePostureDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePostureDeployment(request: r, options: o)
        })
    }

    public func listPostureTemplates(
      request: ListPostureTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.ListPostureTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPostureTemplates",
        action: {
          (r: ListPostureTemplatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecuritypostureV1.ListPostureTemplatesResponse
          in
          return try await self.inner.listPostureTemplates(request: r, options: o)
        })
    }

    public func getPostureTemplate(
      request: GetPostureTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.PostureTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPostureTemplate",
        action: {
          (r: GetPostureTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecuritypostureV1.PostureTemplate
          in
          return try await self.inner.getPostureTemplate(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
