// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol SecurityPostureStub: Sendable {
    func listPostures(
      request: ListPosturesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.ListPosturesResponse

    func listPostureRevisions(
      request: ListPostureRevisionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.ListPostureRevisionsResponse

    func getPosture(
      request: GetPostureRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.Posture

    func createPosture(
      request: CreatePostureRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updatePosture(
      request: UpdatePostureRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deletePosture(
      request: DeletePostureRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func extractPosture(
      request: ExtractPostureRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listPostureDeployments(
      request: ListPostureDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.ListPostureDeploymentsResponse

    func getPostureDeployment(
      request: GetPostureDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.PostureDeployment

    func createPostureDeployment(
      request: CreatePostureDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updatePostureDeployment(
      request: UpdatePostureDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deletePostureDeployment(
      request: DeletePostureDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listPostureTemplates(
      request: ListPostureTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.ListPostureTemplatesResponse

    func getPostureTemplate(
      request: GetPostureTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecuritypostureV1.PostureTemplate

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
